import Providers from '@/components/Providers';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'code_room',
  description: 'Generated by create next app',
  icons: {
    icon: '/logo_icon.png'
  }
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`w-full p-0 m-0 bg-zinc-950 ${inter.className}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
